name: sensor.youtube
description: A platform which give you info about the newest video on a channel.
type: component
keywords:
  - sensor
  - youtube
author:
  name: ludeeus
  email: ludeeus@gmail.com
  homepage: https://ludeeus.github.io
license: MIT
files:
  - custom_components/youtube/sensor.py